export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_YEAR_FILTER = 'SET_YEAR_FILTER';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';